[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "http://lds02.uarg.unpa.edu.ar/Vesta/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200